name: Release Shared Types Package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Use Node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Get diff
      uses: technote-space/get-diff-action@v4
      with:
        FILES: |
          sub-package/main.js
    
    - name: Conditional
      if: env.GIT_DIFF
      run: |
        echo 'found diff: ${env.GIT_DIFF}'

