name: Release Shared Types Package
on:
  push:
    paths:
    - "sub-package/*"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Use Node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      working-directory: ./sub-package
      run: npx semantic-release

